### ISSUE TITLE
Code missing, links broken

### ISSUE THREAD

**Issue by JonathanRennison** [2-IMMERSE/cloud-sync#1]
The code seems to be missing, there are only readme files

A link in client-api.md points to gitlab-ext.irt.de

Other intra-repo links point to non-existent files

**Comment by ramdhany** [comment]
Code sanitisation is currently in progress. Will be released soon.

**Comment by ramdhany** [comment]
Code added and usage instructions updated. Links to  gitlab-ext.irt.de removed.
